### ISSUE TITLE
Script for 3 views on DTU dataset

### ISSUE THREAD

**Issue by yh-yoon** [Open3DVLab/HiSplat#3]
Thanks for your nice work! Could you provide the script and dataloader for 3 views on DTU dataset?

**Comment by tsj-001** [comment]
Hi, thanks for your attention! We will update the testing script for 3 views on DTU dataset soon (within 2 days). However, because HiSplat is not specifically designed for NVS from 3 views, the improvement is not significant compared with the 2-view setting.

**Comment by yh-yoon** [comment]
Thanks for your quick feedback!
